django_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('shop.urls')),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop.views import ProductsList, ItemDetail, ShopCategory, ShopSearch, ShopFavorite, \
    UserBasket, add_favorite_view, delete_favorite_view, check_favorite_view, add_to_basket_view, \
    delete_from_basket_view, check_basket_view

urlpatterns = [
    path('', ProductsList.as_view(), name='product_list'),
    path('<str:slug>', ShopCategory.as_view(), name='shop_category'),
    path('search/', ShopSearch.as_view(), name='search'),
    path('favorite/', ShopFavorite.as_view(), name='favorite'),
    path('basket/', UserBasket.as_view(), name='basket'),
    path('product/<int:pk>/', ItemDetail.as_view(), name='item_detail'),
    path('product/add-favorite/', add_favorite_view, name='add_favorite'),
    path('product/delete-favorite/', delete_favorite_view, name='delete_favorite'),
    path('product/check-favorite/<int:item_pk>/', check_favorite_view, name='check_favorite'),
    path('product/add-to-baket', add_to_basket_view, name='add_to_basket'),
    path('product/delete-from-baket', delete_from_basket_view, name='delete_from_basket'),
    path('product/check-basket/<int:item_pk>/', check_basket_view, name='check_basket'),
]

shop/models.py
"""
Import required libraries for models
"""
from mptt.models import MPTTModel
from mptt.fields import TreeForeignKey, TreeManyToManyField

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg
from django.db import models
from django.urls import reverse

from django_shop import settings


class Category(MPTTModel):
    """
    Model to represent a category in a hierarchy with MPTT (Modified Preorder Tree Traversal)
    """
    name = models.CharField(
        max_length=32,
        verbose_name='Name',
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
    )
    slug = models.SlugField(
        max_length=40,
        verbose_name='url',
        unique=True,
    )

    class MPTTMeta:
        """
        Metaclass to control the order of insertion of categories
        """
        order_insertion_by = ['name']

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        """
        Return the URL to view a category
        """
        return reverse('shop_category', kwargs={'slug': self.slug})


class Item(models.Model):
    """
    Model to represent a product
    """
    title = models.CharField(
        max_length=124,
        verbose_name='Title'
    )
    category = TreeManyToManyField(
        Category,
        verbose_name='Category',
        related_name='category',
    )
    description = models.TextField(
        verbose_name='Description'
    )
    price = models.DecimalField(
        verbose_name='Price',
        max_digits=8,
        decimal_places=2,
        default=0
    )
    salesman = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='items',
        verbose_name='salesman',
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        verbose_name='Created',
        auto_now_add=True
    )

    class Meta:
        """
        Metaclass to control the order of insertion of items
        """
        ordering = ['created_at']

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        """
        Return the URL to view the item detail
        """
        return reverse('item_detail', kwargs={'pk': self.pk})

    def get_avg_rate(self):
        """
        Return the average rate of all reviews for the item
        """
        return Review.objects.filter(product=self).aggregate(Avg('rate'))['rate__avg']


class ProductGallery(models.Model):
    """
    Model for Product Gallery images
    """
    image = models.ImageField(
        upload_to='gallery_product',
        verbose_name='Image'
    )
    product = models.ForeignKey(
        Item,
        related_name='image',
        verbose_name='Product',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.product}'


class Review(models.Model):
    """
    Model for Review of items
    """
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='review',
        verbose_name='Author',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Item,
        related_name='review',
        verbose_name='Product',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name='text'
    )
    rate = models.SmallIntegerField(
        verbose_name='Rate',
        default=0,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100)
        ]
    )
    created_at = models.DateTimeField(
        verbose_name='created',
        auto_now_add=True
    )

    class Meta:
        """
        Metaclass to control the order of insertion of reviews
        """
        ordering = ['created_at']

    def __str__(self):
        return f'{self.product}'


class Favorite(models.Model):
    """
    Model for storing user favorite items
    """
    item = models.ForeignKey(
        Item,
        related_name='favorite',
        verbose_name='Item',
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='favorite',
        verbose_name='User',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.item}'


class Purchase(models.Model):
    """
    Model for storing user purchases
    """
    item = models.ManyToManyField(
        Item,
        related_name='purchase',
        verbose_name='Item',
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        default=None,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    is_delivery = models.BooleanField(
        verbose_name='Is Delivery',
    )
    total_price = models.DecimalField(
        verbose_name='Total price',
        max_digits=12,
        decimal_places=2
    )
    created_at = models.DateTimeField(
        verbose_name='Created at',
        auto_now_add=True,
    )
    email = models.EmailField(
        verbose_name='Email',
    )
    phone = models.BigIntegerField(
        verbose_name='Phone',
        null=True,
        blank=True
    )
    country = models.CharField(
        max_length=64,
        verbose_name='Country',
        null=True,
        blank=True
    )
    city = models.CharField(
        max_length=24,
        verbose_name='City',
        null=True,
        blank=True
    )
    street = models.CharField(
        max_length=128,
        verbose_name='Street',
        null=True,
        blank=True
    )

    class Meta:
        """
        Metaclass to control the order of insertion of purchases
        """
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.email}'

shop/forms.py
"""
Import required libraries for forms
"""
from django import forms

from shop.models import Review, Purchase

SORT = [
    ('1', 'Сначала недорогие'),
    ('2', 'Сначала дорогие'),
    ('3', 'Сначала популярные'),
    ('4', 'Сначала обсуждаемые'),
    ('5', 'Сначала с лучшей оценкой')
]


class FilterProducts(forms.Form):
    """
    Form to filter products based on price and sort
    """
    min_price = forms.IntegerField(
        label='Минимальная цена',
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '0'})
    )
    max_price = forms.IntegerField(
        label='Максимальная цена',
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '999999'})
    )
    sort = forms.ChoiceField(
        label='Сортировка',
        widget=forms.RadioSelect,
        required=False,
        choices=SORT
    )


class ReviewForm(forms.ModelForm):
    """
    Form to submit a review for a product
    """

    class Meta:
        """
        Class to description of fields
        """
        model = Review
        fields = ('rate', 'text')
        widgets = {
            'rate': forms.NumberInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }


class PurchaseForm(forms.ModelForm):
    """
    Form to purchase an item
    """

    class Meta:
        """
        Class to description of fields
        """
        model = Purchase
        fields = ('is_delivery', 'email', 'phone', 'country', 'city', 'street')
        widgets = {
            'is_delivery': forms.CheckboxInput(attrs={'class': 'form-check-input',
                                                      'checked': True}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
        }

shop/views.py
"""
The necessary imports for the shop view module
"""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, CreateView

from shop.filters import get_item_filter, get_items_by_filter, get_items_by_category, get_search_items, \
    get_favorite_items
from shop.forms import FilterProducts, ReviewForm, PurchaseForm
from shop.models import Item
from shop.sevices import get_items_from_basket, create_purchase, add_review, add_favorite, delete_favorite, \
    check_favorite, add_to_basket, delete_from_basket


class BaseShop(ListView, FormView):
    """
    The base view for other list views
    """
    model = Item
    template_name = 'shop/products.html'
    context_object_name = 'products'
    paginate_by = 10
    allow_empty = True
    form_class = FilterProducts

    def get_initial(self):
        return get_item_filter(self.request)

    def get_queryset(self):
        sort = self.get_initial()
        return get_items_by_filter(sort)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        params = self.request.GET.items()
        params_str = ''.join([f'&{key}={value}' for key, value in params if key != 'page'])
        context['params'] = params_str
        return context


class ProductsList(BaseShop):
    """
    View displays the entire list of items for sale
    """


class ShopCategory(BaseShop):
    """
    View filters the items based on a specific category
    """

    def get_queryset(self):
        items = super().get_queryset()
        return get_items_by_category(items, category=self.kwargs['slug'])


class ShopSearch(BaseShop):
    """
    View filters the items based on a search term
    """

    def get_queryset(self):
        search = self.request.GET.get('s', '')
        items = super().get_queryset()
        return get_search_items(items, search=search)


class ShopFavorite(LoginRequiredMixin, BaseShop):
    """
    View displays the list of favorite items for the logged-in user
    """

    def get_queryset(self):
        items = super().get_queryset()
        return get_favorite_items(items, self.request.user.pk)


class UserBasket(CreateView, ListView):
    """
    View displays the items in the user's basket and allows the user to purchase it
    """
    model = Item
    template_name = 'shop/basket.html'
    context_object_name = 'products'
    allow_empty = True

    form_class = PurchaseForm
    success_url = reverse_lazy('basket')

    def get_queryset(self):
        return get_items_from_basket(self.request)

    def form_valid(self, form):
        create_purchase(form, self.request)
        self.request.session['basket'] = []
        messages.success(self.request, 'Ваш заказ успешно оформлен!')
        return super().form_valid(form)


class ItemDetail(DetailView, CreateView):
    """
    View for a specific Item instance with adding a review for the item
    """
    model = Item
    template_name = 'shop/product_detail.html'
    context_object_name = 'product'
    form_class = ReviewForm

    def form_invalid(self, form):
        messages.error(self.request, 'Ошибка при добавлении комментария')
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', '/'))

    def form_valid(self, form):
        add_review(form, self.request.user.id, self.get_object().id)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', '/'))


@login_required
def add_favorite_view(request):
    """
    Add an Item to the user's favorite list
    """
    if request.method == 'POST':
        add_favorite(item_id=request.POST.get('item'), user_id=request.user.pk)
        return JsonResponse({'success': True})


@login_required
def delete_favorite_view(request):
    """
    Delete an Item from the user's favorite list
    """
    if request.method == 'POST':
        delete_favorite(item_id=request.POST.get('item'), user_id=request.user.pk)
        return JsonResponse({'success': True})


def check_favorite_view(request, item_pk):
    """
    Check if an Item is in the user's favorite list
    """
    if request.method == 'GET':
        return JsonResponse({'is_favorite': check_favorite(item_pk, request.user.pk)})


def add_to_basket_view(request, item_id=None):
    """
    Add an Item to the user's basket (stored in the session)
    """
    add_to_basket(request, item_id)
    return JsonResponse({'success': True})


def delete_from_basket_view(request):
    """
    Remove an item from the basket (stored in the session)
    """
    delete_from_basket(request)
    return JsonResponse({'success': True})


def check_basket_view(request, item_pk):
    """
    Check if an item is in the basket (stored in the session)
    """
    if request.method == 'GET':
        basket = request.session.get('basket', [])
        in_basket = bool(item_pk in basket)
        return JsonResponse({'in_basket': in_basket})

templates/shop/basket.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        {% for product in products %}
            {% if forloop.first %}
                <div class="row">
                    <div class="col-2 h4">Изображение</div>
                    <div class="col-6 h4 text-center">Товар</div>
                    <div class="col-2 h4">Цена</div>
                    <div class="col-2 h4">Удалить</div>
                </div>
            {% endif %}
            <div class="row mt-3" id="product_{{ product.pk }}">
                <div class="col-2" style="height: 100px">
                    <img src="{{ product.image.first.image.url }}" class="img-fluid rounded-start h-100"
                         alt="Фото">
                </div>
                <div class="col-6 d-flex align-items-center" style="height: 100px">
                    <a href="{{ product.get_absolute_url }}" class="h5">{{ product.title }}</a>
                </div>
                <div class="col-2 d-flex align-items-center" style="height: 100px">
                    <p class="h5"><span class="item_price">{{ product.price }}</span> Р</p>
                </div>
                <div class="col-2 d-flex pt-4" style="height: 100px">
                    <form method="post" class="delete_btn" data-product-id="{{ product.pk }}">
                        {% csrf_token %}
                        <button class="btn">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                                 class="bi bi-x-lg" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M13.854 2.146a.5.5 0 0 1 0 .708l-11 11a.5.5 0 0 1-.708-.708l11-11a.5.5 0 0 1 .708 0Z"/>
                                <path fill-rule="evenodd"
                                      d="M2.146 2.146a.5.5 0 0 0 0 .708l11 11a.5.5 0 0 0 .708-.708l-11-11a.5.5 0 0 0-.708 0Z"/>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>
            {% if forloop.last %}
                <div class="row mt-3">
                    <form method="post" id="purchase_form" class="form-control">
                        {% csrf_token %}
                        <div class="mt-3">
                            <label for="id_is_delivery" class="">Доставка:</label>
                            {{ form.is_delivery }}
                        </div>
                        <div class="mt-2">
                            <label for="id_email">Email:</label>
                            {{ form.email }}
                        </div>

                        <div class="mt-3">
                            <label for="id_phone">Телефон:</label>
                            {{ form.phone }}
                        </div>
                        <div id="delivery_data" class="">
                            <div class="mt-3">
                                <label for="id_country">Страна:</label>
                                {{ form.country }}
                            </div>

                            <div class="mt-3">
                                <label for="id_city">Город:</label>
                                {{ form.city }}
                            </div>

                            <div class="mt-3">
                                <label for="id_street">Улица:</label>
                                {{ form.street }}
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="col-auto">
                                <input type="submit" value="Оформить заказ" class="btn btn-primary">
                            </div>
                            <div class="col-auto">
                                <p class="h3">Сумма: <span id="sum_price"></span> Р</p>
                            </div>
                        </div>
                    </form>
                </div>
            {% endif %}
        {% empty %}
            <p class="h5">Тут ничего нет(</p>
        {% endfor %}
    </div>
    <script>
        $(document).ready(function () {
            let item_id
            let sum_price = 0
            $('.item_price').each(function (index, element) {
                sum_price += parseFloat($(element).text())
            })
            $('#sum_price').text(sum_price)
            $('.delete_btn').submit(function (e) {
                item_id = $(this).attr('data-product-id')
                e.preventDefault()
                $.ajax({
                    type: 'POST',
                    url: `{% url 'delete_from_basket' %}`,
                    data: {
                        'item': $(this).attr('data-product-id'),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType: 'json',
                    success: function (data) {
                        let sum_price = 0
                        $('#product_' + item_id).remove()
                        if ($('.item_price').length === 0) {
                            $('#purchase_form').remove()
                        } else {
                            $('.item_price').each(function (index, element) {
                                sum_price += parseFloat($(element).text())
                            })
                            $('#sum_price').text(sum_price)
                            console.log(data.message);
                        }
                    }
                });
            });
            $('#id_is_delivery').click(function (e) {
                console.log($(this).attr('checked'))
                if ($(this).attr('checked')) {
                    $(this).attr('checked', false)
                    $('#delivery_data').attr('class', 'visually-hidden')
                } else {
                    $(this).attr('checked', true)
                    $('#delivery_data').attr('class', '')
                }
            })
        });

    </script>
{% endblock %}

templates/shop/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card mb-3 mx-auto" style="max-width: 1300px;">
        <div class="row g-0">
            <div class="col-xl-5" style="max-height: 500px;">
                <div id="carouselImages" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for image in product.image.all %}
                            <div class="carousel-item {% if forloop.first %} active {% endif %}">
                                <img src="{{ image.image.url }}" class="d-block h-100" alt="Фото"
                                     style="max-height: 500px;">
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselImages"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselImages"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="col-xl-5">
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="text-decoration-none" href="{{ product.get_absolute_url }}">
                            {{ product.title }}</a></h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text h5">
                        {% if product.get_avg_rate %}
                            Оценка: {{ product.get_avg_rate }}
                        {% else %}
                            Нет оценок
                        {% endif %}</p>
                </div>
            </div>
            <div class="col-xl-2 text-center">
                <h5 class="mt-3">{{ product.price }} Р</h5>
                <a href="{% url 'basket'  %}" class="btn btn-outline-success" style="min-width: 110px;">
                    Перейти в корзину
                </a>

                <form method="post" id="basket_btn">
                    {% csrf_token %}
                    <button id="add_to_basket_{{ product.pk }}" class="btn btn-outline-primary mt-2"
                            data-product-id="{{ product.pk }}" style="max-width: 110px;">
                        Добавить в корзину
                    </button>
                </form>


                <div class="mt-2">
                    {% if request.user.is_authenticated %}
                        <form method="post" id="favorite_btn"
                              data-product-id="{{ product.pk }}">
                            {% csrf_token %}
                            <button class="btn btn-link">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                     class="bi bi-star"
                                     viewBox="0 0 16 16">
                                    <path id="path_star" class="hello"
                                          d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                </svg>

                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="card mb-3 mx-auto" style="max-width: 1300px;">
        {% if request.user.is_authenticated %}
            <div class="row mb-3 ps-3 pt-3">
                <span class="h4">Написать отзыв</span>
            </div>
            <form method="post" class="p-3">
                {% csrf_token %}
                <div class="row">
                    <div class="mt-3 col-2 h6">Оценка</div>
                    <div class="mt-2 mb-3 col-auto">
                        {{ form.rate }}
                    </div>
                    <div class="mt-3 col-2">От 0 до 100</div>
                </div>

                <div class="row">
                    <div class="mt-3 col-2 h6">Комментарий</div>
                    <div class="mt-2 mb-3 col-10">
                        {{ form.text }}
                    </div>
                </div>
                <input type="submit" class="btn btn-primary ms-3"/>
            </form>
        {% else %}
            <div class="row mb-3 ps-3 pt-3">
                <span class="h4">Необходимо <a href="{% url 'signin' %}?next={{ request.path }}">войти</a>, чтобы написать отзыв</span>
            </div>
        {% endif %}
    </div>
    <div class="card mb-3 mx-auto" style="max-width: 1300px;">
        <div class="row g-0 ps-3 pt-3">
            <div class="row mb-3">
                <div class="col-12">
                    <span class="h4">Отзывы</span>
                    <hr/>
                </div>
            </div>
            {% for review in product.review.all %}
                <p>
                    <span class="fw-bold">Автор: </span>{{ review.author }}
                </p>
                <p>
                    <span class="fw-bold">Оценка: </span>{{ review.rate }}
                </p>
                <p>
                    <span class="fw-bold">Комментарий: </span>{{ review.text }}
                </p>
                <hr/>
            {% endfor %}
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $.ajax({
                type: 'GET',
                url: `{% url 'check_basket' item_pk=product.pk %}`,
                success: function (data) {
                    if (data['in_basket']) {
                        $(`#add_to_basket_{{ product.pk }}`).attr('class', 'btn btn-primary mt-2')
                        $(`#add_to_basket_{{ product.pk }}`).text('Удалить из корзины')
                    }
                }
            });
            $.ajax({
                type: 'GET',
                url: `{% url 'check_favorite' item_pk=product.pk %}`,
                success: function (data) {
                    if (data['is_favorite']) {
                        $('#path_star').attr("d", "M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z");
                    }
                }
            });

            $('#basket_btn').submit(function (e) {
                let currentValue = $("#add_to_basket_{{ product.pk }}").attr("class");
                let url
                if (currentValue === "btn btn-outline-primary mt-2") {
                    $('#add_to_basket_{{ product.pk }}').attr('class', 'btn btn-primary mt-2')
                    $('#add_to_basket_{{ product.pk }}').text('Удалить из корзины')
                    url = `{% url 'add_to_basket' %}`
                } else {
                    $(`#add_to_basket_{{ product.pk }}`).attr('class', 'btn btn-outline-primary mt-2')
                    $(`#add_to_basket_{{ product.pk }}`).text('Добавить в корзину')
                    url = `{% url 'delete_from_basket' %}`
                }
                e.preventDefault()
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'item': $('#add_to_basket_{{ product.pk }}').attr('data-product-id'),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType: 'json',
                    success: function (data) {
                        console.log(data.message);
                    }
                });
            });


            $('#favorite_btn').submit(function (e) {
                let currentValue = $("#path_star").attr("d");
                let url
                if (currentValue.startsWith("M3.612")) {
                    $('#path_star').attr("d", "M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z");
                    url = `{% url 'delete_favorite' %}`
                } else {
                    $('#path_star').attr("d", "M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z");
                    url = `{% url 'add_favorite' %}`
                }
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'item': $(this).attr('data-product-id'),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType: 'json',
                    success: function (data) {
                        console.log(data.message);
                    }
                });
            });
        });

    </script>
{% endblock %}